apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: pipelines
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: {{ toJson .Values.command }}
