global:
  imagePullPolicy: IfNotPresent
  serviceOwnership:
    redpanda: platform-managed
    redis: platform-managed
    qdrant: platform-managed
    mlflow: app-managed
    observability: platform-managed
  endpoints:
    broker: redpanda.demo.svc.cluster.local:9092
    redis: redis.demo.svc.cluster.local:6379
    qdrant: http://qdrant.demo.svc.cluster.local:6333
    mlflow: http://mlflow.demo.svc.cluster.local:5001
